# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NpYcLrxFsI9ImguzBgYFcIFesryOsoWD
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

umb=pd.read_csv("/content/drive/MyDrive/MLL/books_dataset.csv")

umb.head()

umb.tail

umb.duplicated

umb.describe

umb.info()

umb['rating'].plot(kind='hist', bins=20, edgecolor='black')
plt.title('Histogram of genere to rating')
plt.xlabel('Rating')
plt.ylabel('No of books')
plt.show()

umb.isnull

umb[umb['genre']=='Childrens']